# Generated by Django 5.2.5 on 2025-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
            ],
        ),
    ]
