# Generated by Django 5.2.5 on 2025-08-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='تیتر')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن')),
                ('author', models.CharField(blank=True, default='تیم محتوای طراحان', max_length=100, null=True, verbose_name='نویسنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
