# Generated by Django 5.2.5 on 2025-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
