# Generated by Django 5.2.5 on 2025-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0006_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text="ویژگی\u200cها را با '|' جدا کنید. حداکثر ۹ ویژگی.", verbose_name='ویژگی\u200cها'),
        ),
    ]
