# Generated by Django 5.2.5 on 2025-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0007_product_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=220, verbose_name='نام همکاری')),
                ('image', models.ImageField(upload_to='manager/', verbose_name='تصویر همکار')),
                ('job', models.CharField(max_length=220, verbose_name='فیلد کاری')),
            ],
            options={
                'verbose_name': 'همکاران',
                'verbose_name_plural': 'همکاران',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
    ]
