# Generated by Django 5.2.5 on 2025-09-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0008_about_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برندها', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
