# Generated by Django 5.2.5 on 2025-09-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0009_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='شگفت انگیز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='پیشنهاری'),
        ),
    ]
