# Generated by Django 5.2.5 on 2025-09-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarahan', '0010_alter_category_name_alter_product_is_amazing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='پیشنهادی'),
        ),
    ]
